# Generated by Django 6.0.3 on 2026-03-09 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IN', 'En fase de inscripciones'), ('CO', 'Confirmado'), ('AR', 'Archivado'), ('CA', 'Cancelado')], default='IN', max_length=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.CharField(max_length=255)),
                ('duration_hours', models.PositiveIntegerField()),
                ('modality', models.CharField(choices=[('PR', 'Presencial'), ('VI', 'Virtual'), ('HY', 'Híbrida')], max_length=2)),
                ('location_or_link', models.CharField(max_length=255)),
                ('max_capacity', models.PositiveIntegerField()),
                ('min_inscriptions', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epc_points', models.BooleanField(default=False)),
                ('accreditation_requirements', models.TextField()),
                ('by_contract', models.BooleanField(default=False)),
                ('with_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.category')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('documents', models.FileField(blank=True, null=True, upload_to='enrollment_docs/')),
                ('status', models.CharField(choices=[('PE', 'Pendiente de Revisión'), ('IR', 'Información Requerida'), ('AP', 'Aprobada'), ('RE', 'Rechazada')], default='PE', max_length=2)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attendance_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_document', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_payment', models.FileField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('PE', 'Pendiente de Verificación de Pago'), ('CO', 'Confirmada'), ('RE', 'Pago Rechazado'), ('RIP', 'Reembolso en proceso'), ('RC', 'Reembolso completado')], default='PE', max_length=3)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='events.enrollment')),
            ],
        ),
    ]
